apiVersion: v1
kind: Service
metadata:
  name: kartal-server
  labels:
    app.kubernetes.io/name: kartal-server
spec:
  selector:
    app.kubernetes.io/name: kartal-server
  ports:
    - name: http
      port: 8080
      targetPort: http
